image: docker:latest
services:
  - docker:dind

stages:
  - build

rp2040-build:
  image: lukstep/raspberry-pi-pico-sdk:latest
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. && make -j4
  artifacts:
    paths:
      - build/*.uf2
      - build/*.hex
      - build/*.elf
      - build/*.bin
      - build/*.elf.map
    expire_in: 1 month

