image: docker:latest
services:
  - docker:dind

stages:
  - build

rp2040-build:
  image: lukstep/raspberry-pi-pico-sdk:latest
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. && make -j4
  artifacts:
    paths:
      - build/blink.uf2
      - build/blink.hex
      - build/blink.elf
      - build/blink.bin
      - build/blink.elf.map
    expire_in: 1 month

